
const users = [
    {
      id: 1,
      name: "Bongomin Erick Juma",
      email: "ericbongomin@gmail.com",
      phone: "0775008904",
      subscription: "AiDA",
      password: "123456",
    },
    {
      id: 2,
      name: "Jane Doe",
      email: "jane.doe@example.com",
      phone: "0775008905",
      subscription: "Twogere Standard",
      password: "abcdef",
    },
    {
      id: 3,
      name: "John Smith",
      email: "john.smith@example.com",
      phone: "0775008906",
      subscription: "Twogere Enterprise",
      password: "password123",
    },
    {
      id: 4,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      phone: "0775008907",
      subscription: "YoDegree",
      password: "qwerty",
    },
    {
      id: 5,
      name: "Bob Brown",
      email: "bob.brown@example.com",
      phone: "0775008908",
      subscription: "AiDA",
      password: "letmein",
    },
    {
      id: 6,
      name: "Charlie Davis",
      email: "charlie.davis@example.com",
      phone: "0775008909",
      subscription: "Twogere Standard",
      password: "123qwe",
    },
    {
      id: 7,
      name: "Diana Evans",
      email: "diana.evans@example.com",
      phone: "0775008910",
      subscription: "Twogere Enterprise",
      password: "password1",
    },
    {
      id: 8,
      name: "Ethan Foster",
      email: "ethan.foster@example.com",
      phone: "0775008911",
      subscription: "YoDegree",
      password: "mypassword",
    },
    {
      id: 9,
      name: "Fiona Green",
      email: "fiona.green@example.com",
      phone: "0775008912",
      subscription: "AiDA",
      password: "pass123",
    },
    {
      id: 10,
      name: "George Harris",
      email: "george.harris@example.com",
      phone: "0775008913",
      subscription: "Twogere Standard",
      password: "securepass",
    },
  ];

export default users;